format = """
$directory\
$git_branch\
$git_state\
$git_commit\
$fill\
$nodejs\
$python\
$java\
$c\
$cmd_duration\
$line_break\
$character\
"""

palette = 'tokyo_night'
add_newline = true

[palettes.tokyo_night]
foreground = '#c0caf5'
background = '#1a1b26'
current_line = '#c0caf5'
primary = '#1a1b26'
box = '#2f3549'
blue = '#7aa2f7'
cyan = '#0db9d7'
green = '#9ece6a'
orange = '#ff9e64'
pink = '#bb9af7'
purple = '#9d7cd8'
red = '#f7768e'
yellow = '#e0af68'

[fill]
symbol = ' '

[directory]
format = '(fg:current_line)[î‚¶](fg:pink)[î˜“](fg:primary bg:pink)[î‚´](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[î‚´](fg:box)'
truncation_symbol = '../'
truncation_length = 2

[git_branch]
format = '[ ](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $branch](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'îœ¥'

[git_state]
format = '[ ](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $all_status$ahead_behind](fg:foreground bg:box)[î‚´](fg:box)'
cherry_pick = 'ğŸ’'
rebase = 'ğŸ”„'
merge = 'ğŸ”€'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[nodejs]
format = '(fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ó°™'

[bun]
format = '[ ](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ğŸ”'

[python]
format = '[ ](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'îœ¼'

[java]
format = '[ ](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'îœ¸'

[c]
format = '[ ](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'î˜'

[cmd_duration]
min_time = 500
format = '[ ](fg:current_line)[î‚¶](fg:orange)[ïƒ§](fg:primary bg:orange)[î‚´](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[î‚´](fg:box)'

[character]
success_symbol = '[â¯](fg:bold green)'
error_symbol = '[Ã—](fg:bold red)'